### ISSUE TITLE
Allow loading of higher resolution thumbnail

### ISSUE THREAD

**Issue by emyller** [yetty/django-embed-video#43]
By default, embed-video loads thumbnails from YouTube based on the following format: `'{protocol}://img.youtube.com/vi/{code}/hqdefault.jpg'`.

It would be very good if I could load a higher-res thumbnail. The following string format could be used: `'{protocol}://img.youtube.com/vi/{code}/maxresdefault.jpg'`.

**Comment by DiogoMarques29** [comment]
Hi
How about this? 
http://stackoverflow.com/questions/6471275/python-script-to-see-if-a-web-page-exists-without-downloading-the-whole-page?answertab=active#tab-top

This is a way to check if status code is < 400 without downloading the whole page.

**Comment by DiogoMarques29** [comment]
Hi again

I have found a better solution that works like this:
```
def checkUrl(url):
    import requests
    r = requests.head(url)
    return int(r.status_code) < 400
```

**Comment by yetty** [comment]
Great! Can you create a pull request with this improvement?

**Comment by DiogoMarques29** [comment]
I will as soon as i have some time. Got any ideia when a new release will be available?

**Comment by yetty** [comment]
As soon as the support for Django 1.9 will be added + this functionality, too.
