### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by sunjoomoon** [yetty/django-embed-video#50]
django 1.6.10,  embed_video, VERSION = (0, 10, 'stable')

#models.py
```video = EmbedVideoField(_('video url'), blank=True,null=True)```

When I save the page empty field from admin, below is returned, what could cause this? But if I put youtube url, then it is saved okay and all in good shape.

```
'NoneType' object has no attribute 'strip'
```

**Comment by bee-keeper** [comment]
@sunjoomoon are you using any 3rd party apps? I'm also getting this error but with Django 1.8 and model translation.

**Comment by yetty** [comment]
@sunjoomoon please copy and paste full error stacktrace.

**Comment by bee-keeper** [comment]
I think the issue here is to with initialising with `null=True`, I presume Django does a strip() and this is what causes the error.  

As per the thread [here](https://github.com/deschler/django-modeltranslation/issues/221) remove `null=True` and that fixes the problem.

**Comment by sunjoomoon** [comment]
Long time, yes indeed. somehow at the database level that is not quite happy with ```null``` value. As you said removing ```null=True``` did the job.
